/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.bitfull.iamh;

import de.bitfull.iamh.utils.HumanUtils;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;

import java.io.IOException;
import java.util.function.Supplier;

public class App {
    public static void main(String[] args) {

        App app = new App();
        try {
            app.run();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void run() throws IOException {

        IAMHuman human = new IAMHuman(newFirefox(), HumanUtils
                .readJson("src/main/resources/input.json"));
        human.work();
    }

    private Supplier newFirefox() {
        return newFirefox(true);
    }

    private Supplier newFirefox(boolean jsEnabled) {
        return (Supplier<Object>) () -> {
            FirefoxOptions options = new FirefoxOptions();
            options.addPreference("javascript.enabled", jsEnabled);
            //options.addPreference("network.proxy.type", 1);
            //options.addPreference("network.proxy.socks", "192.168.178.51");
            //options.addPreference("network.proxy.socks_port", 1080);
            return new FirefoxDriver(options);
        };
    }


}